export const selectSigningType = state => state.signing.signingType
export const selectIsSuccessfulSigning = state => state.signing.isSuccessfulSigning
export const selectSubscriberData = state => state.signing.subscriberData
export const selectIsClientHasPep = state => state.signing.isClientHasPep
export const selectIsLoadingCheckIsClientHasPep = state => state.signing.isLoadingCheckIsClientHasPep
export const selectPepNumbers = state => state.signing.pepNumbers
export const selectActivePepNumber = state => state.signing.activePepNumber
export const selectSigningPaperDocuments = state => state.signing.paperDocuments
export const selectIsLoadingGetPepNumbers = state => state.signing.isLoadingGetPepNumbers
export const selectIsLoadingGetSmsCode = state => state.signing.isLoadingGetSmsCode
export const selectIsLoadingGetDocumentCode = state => state.signing.isLoadingGetDocumentCode
export const selectPepCode = state => state.signing.pepCode
export const selectIsLoadingCheckPepCode = state => state.signing.isLoadingCheckPepCode
export const selectIsLoadingGetPaperDocuments = state => state.signing.isLoadingGetPaperDocuments
export const selectIsSigningSkipped = state => state.signing.isSigningSkipped
export const selectIsErrorGetDocumentCode = state => state.signing.isErrorGetDocumentCode
export const selectIsErrorGetPaperDocuments = state => state.signing.isErrorGetPaperDocuments
export const selectSignedDocuments = state => state.signing.signedDocuments
export const selectCommentary = state => state.signing.commentary
