import { object } from 'yup';
import {
  addClientsLastNameValidation,
  addClientsFirstNameValidation,
  addClientPatronymicValidation,
  addClientMobilePhoneValidation,
  addClientEmailValidation,
  addClientInnValidation,
  addClientCountryValidation,
  addClientCityValidation,
  addClientRegionValidation,
  addClientStreetValidation,
  addClientHouseNumberValidation,
  addClientEntranceNumberValidation,
  addClientNumberApartmentValidation,
  addClientPostcodeValidation,
  // addClientPassportNumberValidation,
  // addClientPassportIssuedByValidation,
  // addClientPassportDepartamentCodeValidation,
  // addClientCitizenshipValidation,
  addClientCodewordValidation,
} from './validations';

// TODO рефакторинг валидации
export const addClientsValidation = object().shape(
  // {
  //   lastName: addClientsLastNameValidation,
  //   firstName: addClientsFirstNameValidation,
  //   patronymic: addClientPatronymicValidation,
  //   mobilePhone: addClientMobilePhoneValidation,
  //   email: addClientEmailValidation,
  //   inn: addClientInnValidation,
  //   country: addClientCountryValidation,
  //   city: addClientCityValidation,
  //   region: addClientRegionValidation,
  //   street: addClientStreetValidation,
  //   houseNumber: addClientHouseNumberValidation,
  //   entranceNumber: addClientEntranceNumberValidation,
  //   numberApartment: addClientNumberApartmentValidation,
  //   postcode: addClientPostcodeValidation,
  // passportNumber: addClientPassportNumberValidation,
  // passportIssuedBy: addClientPassportIssuedByValidation,
  // departamentCode: addClientPassportDepartamentCodeValidation,
  // citizenship: addClientCitizenshipValidation,
  //   codeword: addClientCodewordValidation,
  // },
  {
    ['first_name']: addClientsFirstNameValidation,
    ['last_name']: addClientsLastNameValidation,
    patronymic: addClientPatronymicValidation,
    ['mobile_phone']: addClientMobilePhoneValidation,
    email: addClientEmailValidation,
    inn: addClientInnValidation,
    country: addClientCountryValidation,
    region: addClientRegionValidation,
    city: addClientCityValidation,
    street: addClientStreetValidation,
    ['house_number']: addClientHouseNumberValidation,
    ['entrance_number']: addClientEntranceNumberValidation,
    ['apartment_number']: addClientNumberApartmentValidation,
    postcode: addClientPostcodeValidation,
    // passportNumber: addClientPassportNumberValidation,
    // passportIssuedBy: addClientPassportIssuedByValidation,
    codeword: addClientCodewordValidation,
    // passportData: {
    //   number: addClientPassportNumberValidation,
    //   citizenship: addClientCitizenshipValidation,
    //   date_of_issue: string,
    //   issued_by: addClientPassportIssuedByValidation,
    //   department_code: addClientPassportDepartamentCodeValidation,
    // },
  },
  [
    ['postcode', 'postcode'],
    // ['numberApartment', 'numberApartment'],
    // ['entranceNumber', 'entranceNumber'],
    ['apartment_number', 'apartment_number'],
    ['entrance_number', 'entrance_number'],
    ['region', 'region'],
    ['email', 'email'],
    ['patronymic', 'patronymic'],
  ],
);
