export const GET_ORDER = 'broadband/GET_ORDER'
export const GET_ORDER_SUCCESS = 'broadband/GET_ORDER_SUCCESS'
export const GET_ORDER_ERROR = 'broadband/GET_ORDER_ERROR'
export const GET_ORDER_FAILURE = 'broadband/GET_ORDER_FAILURE'

export const CHANGE_ORDER_LOADING_STATUS = 'broadband/CHANGE_ORDER_LOADING_STATUS'
export const CHANGE_CHECK_ADDRESS_STATUS = 'broadband/CHANGE_CHECK_ADDRESS_STATUS'

export const GET_ADDRESS_SUGGESTION = 'broadband/GET_ADDRESS_SUGGESTION'
export const GET_ADDRESS_SUGGESTION_SUCCESS = 'broadband/GET_ADDRESS_SUGGESTION_SUCCESS'
export const GET_ADDRESS_SUGGESTION_ERROR = 'broadband/GET_ADDRESS_SUGGESTION_ERROR'
export const GET_ADDRESS_SUGGESTION_FAILURE = 'broadband/GET_ADDRESS_SUGGESTION_FAILURE'
export const ADD_SUGGESTION_DATA = 'broadband/ADD_SUGGESTION_DATA'

export const RECHECK_ADDRESS = 'broadband/RECHECK_ADDRESS'
export const RECHECK_ADDRESS_SUCCESS = 'broadband/RECHECK_ADDRESS_SUCCESS'
export const RECHECK_ADDRESS_ERROR = 'broadband/RECHECK_ADDRESS_ERROR'
export const RECHECK_ADDRESS_FAILURE = 'broadband/RECHECK_ADDRESS_FAILURE'

export const GET_RTC_KEY = 'broadband/GET_RTC_KEY'
export const GET_RTC_KEY_SUCCESS = 'broadband/GET_RTC_KEY_SUCCESS'
export const GET_RTC_KEY_ERROR = 'broadband/GET_RTC_KEY_ERROR'
export const GET_RTC_KEY_FAILURE = 'broadband/GET_RTC_KEY_FAILURE'

export const CHECK_ADDRESS = 'broadband/CHECK_ADDRESS'
export const CHECK_ADDRESS_SUCCESS = 'broadband/CHECK_ADDRESS_SUCCESS'
export const CHECK_ADDRESS_ERROR = 'broadband/CHECK_ADDRESS_ERROR'
export const CHECK_ADDRESS_FAILURE = 'broadband/CHECK_ADDRESS_FAILURE'

export const CLEAN_CHECK_ADDRESS = 'broadband/CLEAN_CHECK_ADDRESS'

export const GET_SPEED_TO_TECHNOLOGY = 'broadband/GET_SPEED_TO_TECHNOLOGY'
export const GET_SPEED_TO_TECHNOLOGY_ERROR = 'broadband/GET_SPEED_TO_TECHNOLOGY_SUCCESS'
export const GET_SPEED_TO_TECHNOLOGY_FAILURE = 'broadband/GET_SPEED_TO_TECHNOLOGY_FAILURE'
export const GET_SPEED_TO_TECHNOLOGY_SUCCESS = 'broadband/GET_SPEED_TO_TECHNOLOGY_SUCCESS'

export const GET_UPSALE_SPEED_TO_TECHNOLOGY = 'broadband/GET_UPSALE_SPEED_TO_TECHNOLOGY'
export const GET_UPSALE_SPEED_TO_TECHNOLOGY_ERROR = 'broadband/GET_UPSALE_SPEED_TO_TECHNOLOGY_SUCCESS'
export const GET_UPSALE_SPEED_TO_TECHNOLOGY_FAILURE = 'broadband/GET_UPSALE_SPEED_TO_TECHNOLOGY_FAILURE'
export const GET_UPSALE_SPEED_TO_TECHNOLOGY_SUCCESS = 'broadband/GET_UPSALE_SPEED_TO_TECHNOLOGY_SUCCESS'

export const CLEAN_SPEED_TO_TECHNOLOGY = 'broadband/CLEAN_SPEED_TO_TECHNOLOGY'

export const GET_EQUIPMENT_TYPE = 'broadband/GET_EQUIPMENT_TYPE'
export const GET_EQUIPMENT_TYPE_ERROR = 'broadband/GET_EQUIPMENT_TYPE_ERROR'
export const GET_EQUIPMENT_TYPE_FAILURE = 'broadband/GET_EQUIPMENT_TYPE_FAILURE'
export const GET_EQUIPMENT_TYPE_SUCCESS = 'broadband/GET_EQUIPMENT_TYPE_SUCCESS'

export const GET_UPSALE_EQUIPMENT_TYPE = 'broadband/GET_UPSALE_EQUIPMENT_TYPE'
export const GET_UPSALE_EQUIPMENT_TYPE_ERROR = 'broadband/GET_UPSALE_EQUIPMENT_TYPE_ERROR'
export const GET_UPSALE_EQUIPMENT_TYPE_FAILURE = 'broadband/GET_UPSALE_EQUIPMENT_TYPE_FAILURE'
export const GET_UPSALE_EQUIPMENT_TYPE_SUCCESS = 'broadband/GET_UPSALE_EQUIPMENT_TYPE_SUCCESS'

export const EQUIPMENT_OWNERSHIP_FETCH_SUCCESS = 'broadband/EQUIPMENT_OWNERSHIP_FETCH_SUCCESS'
export const EQUIPMENT_OWNERSHIP_FETCH_FAILURE = 'broadband/EQUIPMENT_OWNERSHIP_FETCH_FAILURE'

export const CHANGE_MAIN_FORM = 'broadband/CHANGE_MAIN_FORM'
export const CHANGE_PERSONAL_FORM = 'broadband/CHANGE_PERSONAL_FORM'
export const CHANGE_REASONS_FORM = 'broadband/CHANGE_REASONS_FORM'
export const CHANGE_CONTEXT_STATE = 'broadband/CHANGE_CONTEXT_STATE'
export const CHANGE_AUTO_ACTIONS_STATE = 'broadband/CHANGE_AUTO_ACTIONS_STATE'

export const CLEAN_ADDRESS_FORM = 'broadband/CLEAN_ADDRESS_FORM'
export const CHANGE_FORM_VALUES = 'broadband/CHANGE_FORM_VALUES'

export const CLEAN_ORPON_ID = 'broadband/CLEAN_ORPON_ID'

export const PERFORM_ORDER = 'broadband/PERFORM_ORDER'
export const PERFORM_ORDER_SUCCESS = 'broadband/PERFORM_ORDER_SUCCESS'
export const PERFORM_ORDER_ERROR = 'broadband/PERFORM_ORDER_ERROR'
export const PERFORM_ORDER_FAILURE = 'broadband/PERFORM_ORDER_FAILURE'

export const GET_DOCUMENT_TYPES = 'broadband/GET_DOCUMENT_TYPES'
export const GET_DOCUMENT_TYPES_SUCCESS = 'broadband/GET_DOCUMENT_TYPES_SUCCESS'
export const GET_DOCUMENT_TYPES_ERROR = 'broadband/GET_DOCUMENT_TYPES_ERROR'
export const GET_DOCUMENT_TYPES_FAILURE = 'broadband/GET_DOCUMENT_TYPES_FAILURE'

export const GET_DOCUMENT = 'broadband/GET_DOCUMENT'
export const GET_DOCUMENT_SUCCESS = 'broadband/GET_DOCUMENT_SUCCESS'
export const GET_DOCUMENT_ERROR = 'broadband/GET_DOCUMENT_ERROR'
export const GET_DOCUMENT_FAILURE = 'broadband/GET_DOCUMENT_FAILURE'

export const GET_TIMESLOTS = 'broadband/GET_TIMESLOTS'
export const GET_TIMESLOTS_SUCCESS = 'broadband/GET_TIMESLOTS_SUCCESS'
export const GET_TIMESLOTS_ERROR = 'broadband/GET_TIMESLOTS_ERROR'
export const GET_TIMESLOTS_FAILURE = 'broadband/GET_TIMESLOTS_FAILURE'

export const RESERVE_TIMESLOT = 'broadband/RESERVE_TIMESLOT'
export const RESERVE_TIMESLOT_SUCCESS = 'broadband/RESERVE_TIMESLOT_SUCCESS'
export const RESERVE_TIMESLOT_ERROR = 'broadband/RESERVE_TIMESLOT_ERROR'
export const RESERVE_TIMESLOT_FAILURE = 'broadband/RESERVE_TIMESLOT_FAILURE'

export const DELETE_TIMESLOT = 'broadband/DELETE_TIMESLOT'
export const DELETE_TIMESLOT_SUCCESS = 'broadband/DELETE_TIMESLOT_SUCCESS'
export const DELETE_TIMESLOT_ERROR = 'broadband/DELETE_TIMESLOT_ERROR'
export const DELETE_TIMESLOT_FAILURE = 'broadband/DELETE_TIMESLOT_FAILURE'

export const CHECK_AUTO_INTERVAL = 'broadband/CHECK_AUTO_INTERVAL'
export const CHECK_AUTO_INTERVAL_SUCCESS = 'broadband/CHECK_AUTO_INTERVAL_SUCCESS'
export const CHECK_AUTO_INTERVAL_ERROR = 'broadband/CHECK_AUTO_INTERVAL_ERROR'
export const CHECK_AUTO_INTERVAL_FAILURE = 'broadband/CHECK_AUTO_INTERVAL_FAILURE'

export const CHANGE_TIMESLOT = 'broadband/CHANGE_TIMESLOT'
export const CHANGE_TIMESLOT_SUCCESS = 'broadband/CHANGE_TIMESLOT_SUCCESS'
export const CHANGE_TIMESLOT_ERROR = 'broadband/CHANGE_TIMESLOT_ERROR'
export const CHANGE_TIMESLOT_FAILURE = 'broadband/CHANGE_TIMESLOT_FAILURE'

export const MODIFY_ORDER_TIMESLOT = 'broadband/MODIFY_ORDER_TIMESLOT'
export const MODIFY_ORDER_TIMESLOT_SUCCESS = 'broadband/MODIFY_ORDER_TIMESLOT_SUCCESS'
export const MODIFY_ORDER_TIMESLOT_ERROR = 'broadband/MODIFY_ORDER_TIMESLOT_ERROR'
export const MODIFY_ORDER_TIMESLOT_FAILURE = 'broadband/MODIFY_ORDER_TIMESLOT_FAILURE'

export const CHANGE_ORDER_WAIT_STATE = 'broadband/CHANGE_ORDER_WAIT_STATE'
export const CHANGE_ORDER_WAIT_STATE_SUCCESS = 'broadband/CHANGE_ORDER_WAIT_STATE_SUCCESS'
export const CHANGE_ORDER_WAIT_STATE_ERROR = 'broadband/CHANGE_ORDER_WAIT_STATE_ERROR'
export const CHANGE_ORDER_WAIT_STATE_FAILURE = 'broadband/CHANGE_ORDER_WAIT_STATE_FAILURE'

export const TRANSFER_ORDER = 'broadband/TRANSFER_ORDER'
export const TRANSFER_ORDER_SUCCESS = 'broadband/TRANSFER_ORDER_SUCCESS'
export const TRANSFER_ORDER_ERROR = 'broadband/TRANSFER_ORDER_ERROR'
export const TRANSFER_ORDER_FAILURE = 'broadband/TRANSFER_ORDER_FAILURE'

export const CANCEL_ORDER = 'broadband/CANCEL_ORDER'
export const CANCEL_ORDER_SUCCESS = 'broadband/CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_ERROR = 'broadband/CANCEL_ORDER_ERROR'
export const CANCEL_ORDER_FAILURE = 'broadband/CANCEL_ORDER_FAILURE'

export const DELETE_ORDER = 'broadband/DELETE_ORDER'
export const DELETE_ORDER_SUCCESS = 'broadband/DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'broadband/DELETE_ORDER_ERROR'
export const DELETE_ORDER_FAILURE = 'broadband/DELETE_ORDER_FAILURE'

export const GET_BROADBAND_TARIFFS = 'broadband/GET_BROADBAND_TARIFFS'
export const GET_BROADBAND_TARIFFS_SUCCESS = 'broadband/GET_BROADBAND_TARIFFS_SUCCESS'
export const GET_BROADBAND_TARIFFS_ERROR = 'broadband/GET_BROADBAND_TARIFFS_ERROR'
export const GET_BROADBAND_TARIFFS_FAILURE = 'broadband/GET_BROADBAND_TARIFFS_FAILURE'

export const GET_MACRO_REGIONS = 'broadband/GET_MACRO_REGIONS'
export const GET_MACRO_REGIONS_SUCCESS = 'broadband/GET_MACRO_REGIONS_SUCCESS'
export const GET_MACRO_REGIONS_ERROR = 'broadband/GET_MACRO_REGIONS_ERROR'
export const GET_MACRO_REGIONS_FAILURE = 'broadband/GET_MACRO_REGIONS_FAILURE'

export const GET_REGIONS = 'broadband/GET_REGIONS'
export const GET_REGIONS_SUCCESS = 'broadband/GET_REGIONS_SUCCESS'
export const GET_REGIONS_ERROR = 'broadband/GET_REGIONS_ERROR'
export const GET_REGIONS_FAILURE = 'broadband/GET_REGIONS_FAILURE'

export const GET_REGION_ISO_CODE = 'broadband/GET_REGION_ISO_CODE'
export const GET_REGION_ISO_CODE_SUCCESS = 'broadband/GET_REGION_ISO_CODE_SUCCESS'
export const GET_REGION_ISO_CODE_ERROR = 'broadband/GET_REGION_ISO_CODE_ERROR'
export const GET_REGION_ISO_CODE_FAILURE = 'broadband/GET_REGION_ISO_CODE_FAILURE'

export const SET_CONSTRUCTOR_PRICE = 'broadband/RECALCULATE_FULL_PRICE'

export const GET_ORDER_LIST = 'broadband/GET_ORDER_LIST'
export const GET_ORDER_LIST_SUCCESS = 'broadband/GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_ERROR = 'broadband/GET_ORDER_LIST_ERROR'
export const GET_ORDER_LIST_FAILURE = 'broadband/GET_ORDER_LIST_FAILURE'

export const GET_HANDBOOKS = 'broadband/GET_HANDBOOKS'
export const GET_HANDBOOKS_SUCCESS = 'broadband/GET_HANDBOOKS_SUCCESS'
export const GET_HANDBOOKS_ERROR = 'broadband/GET_HANDBOOKS_ERROR'
export const GET_HANDBOOKS_FAILURE = 'broadband/GET_HANDBOOKS_FAILURE'

export const GET_STATUS_REASONS = 'broadband/GET_STATUS_REASONS'
export const GET_STATUS_REASONS_SUCCESS = 'broadband/GET_STATUS_REASONS_SUCCESS'
export const GET_STATUS_REASONS_ERROR = 'broadband/GET_STATUS_REASONS_ERROR'
export const GET_STATUS_REASONS_FAILURE = 'broadband/GET_STATUS_REASONS_FAILURE'

export const GET_OPERATION_REASONS = 'broadband/GET_OPERATION_REASONS'
export const GET_OPERATION_REASONS_SUCCESS = 'broadband/GET_OPERATION_REASONS_SUCCESS'
export const GET_OPERATION_REASONS_ERROR = 'broadband/GET_OPERATION_REASONS_ERROR'
export const GET_OPERATION_REASONS_FAILURE = 'broadband/GET_OPERATION_REASONS_FAILURE'

export const GET_ORDER_RTC_STATUSES = 'broadband/GET_ORDER_RTC_STATUSES'
export const GET_ORDER_RTC_STATUSES_SUCCESS = 'broadband/GET_ORDER_RTC_STATUSES_SUCCESS'
export const GET_ORDER_RTC_STATUSES_ERROR = 'broadband/GET_ORDER_RTC_STATUSES_ERROR'
export const GET_ORDER_RTC_STATUSES_FAILURE = 'broadband/GET_ORDER_RTC_STATUSES_FAILURE'

export const GET_ORDER_HISTORY = 'broadband/GET_ORDER_HISTORY'
export const GET_ORDER_HISTORY_SUCCESS = 'broadband/GET_ORDER_HISTORY_SUCCESS'
export const GET_ORDER_HISTORY_ERROR = 'broadband/GET_ORDER_HISTORY_ERROR'
export const GET_ORDER_HISTORY_FAILURE = 'broadband/GET_ORDER_HISTORY_FAILURE'

export const GET_ORDER_COMMENT_HISTORY = 'broadband/GET_ORDER_COMMENT_HISTORY'
export const GET_ORDER_COMMENT_HISTORY_SUCCESS = 'broadband/GET_ORDER_COMMENT_HISTORY_SUCCESS'
export const GET_ORDER_COMMENT_HISTORY_ERROR = 'broadband/GET_ORDER_COMMENT_HISTORY_ERROR'
export const GET_ORDER_COMMENT_HISTORY_FAILURE = 'broadband/GET_ORDER_COMMENT_HISTORY_FAILURE'

export const GET_AVAILABLE_TARIFFS = 'broadband/GET_AVAILABLE_TARIFFS'
export const GET_AVAILABLE_TARIFFS_SUCCESS = 'broadband/GET_AVAILABLE_TARIFFS_SUCCESS'
export const GET_AVAILABLE_TARIFFS_ERROR = 'broadband/GET_AVAILABLE_TARIFFS_ERROR'
export const GET_AVAILABLE_TARIFFS_FAILURE = 'broadband/GET_AVAILABLE_TARIFFS_FAILURE'

export const CHECK_SUBSCRIBER_TARIFF = 'broadband/CHECK_SUBSCRIBER_TARIFF'
export const CHECK_SUBSCRIBER_TARIFF_SUCCESS = 'broadband/CHECK_SUBSCRIBER_TARIFF_SUCCESS'
export const CHECK_SUBSCRIBER_TARIFF_ERROR = 'broadband/CHECK_SUBSCRIBER_TARIFF_ERROR'
export const CHECK_SUBSCRIBER_TARIFF_FAILURE = 'broadband/CHECK_SUBSCRIBER_TARIFF_FAILURE'

export const GET_SERVICES_FOR_SELL = 'broadband/SERVICES_FOR_SELL'
export const GET_SERVICES_FOR_SELL_SUCCESS = 'broadband/SERVICES_FOR_SELL_SUCCESS'
export const GET_SERVICES_FOR_SELL_ERROR = 'broadband/SERVICES_FOR_SELL_ERROR'
export const GET_SERVICES_FOR_SELL_FAILURE = 'broadband/SERVICES_FOR_SELL_FAILURE'

export const CHANGE_BROADBAND_SERVICES = 'broadband/CHANGE_BROADBAND_SERVICES'
export const CHANGE_BROADBAND_SERVICES_SUCCESS = 'broadband/CHANGE_BROADBAND_SERVICES_SUCCESS'
export const CHANGE_BROADBAND_SERVICES_ERROR = 'broadband/CHANGE_BROADBAND_SERVICES_ERROR'
export const CHANGE_BROADBAND_SERVICES_FAILURE = 'broadband/CHANGE_BROADBAND_SERVICES_FAILURE'

export const CHANGE_TARIFF_MODAL_VISIBILITY = 'broadband/CHANGE_TARIFF_MODAL_VISIBILITY'
export const CHANGE_NUMBER_MODAL_VISIBILITY = 'broadband/CHANGE_NUMBER_MODAL_VISIBILITY'
export const CHANGE_NUMBER_MODAL_TYPE = 'broadband/CHANGE_NUMBER_MODAL_TYPE'
export const CHANGE_MANUAL_UPSALE_MODAL_VISIBILITY = 'broadband/CHANGE_MANUAL_UPSALE_MODAL_VISIBILITY'
export const CHANGE_AUTO_UPSALE_MODAL_VISIBILITY = 'broadband/CHANGE_AUTO_UPSALE_MODAL_VISIBILITY'
export const CHANGE_RESCHEDULE_MODAL_VISIBILITY = 'broadband/CHANGE_RESCHEDULE_MODAL_VISIBILITY'
export const CHANGE_CANCEL_AUTO_UPSALE_MODAL_VISIBILITY = 'broadband/CHANGE_CANCEL_AUTO_UPSALE_MODAL_VISIBILITY'

export const MODIFY_RTC_DATA = 'broadband/MODIFY_RTC_DATA'
export const MODIFY_RTC_DATA_SUCCESS = 'broadband/MODIFY_RTC_DATA_SUCCESS'
export const MODIFY_RTC_DATA_ERROR = 'broadband/MODIFY_RTC_DATA_ERROR'
export const MODIFY_RTC_DATA_FAILURE = 'broadband/MODIFY_RTC_DATA_FAILURE'

export const GET_MSISDN = 'broadband/GET_MSISDN'
export const GET_MSISDN_SUCCESS = 'broadband/GET_MSISDN_SUCCESS'
export const GET_MSISDN_ERROR = 'broadband/GET_MSISDN_ERROR'
export const GET_MSISDN_FAILURE = 'broadband/GET_MSISDN_FAILURE'

export const RESERVE_MSISDN = 'broadband/RESERVE_MSISDN'
export const RESERVE_MSISDN_SUCCESS = 'broadband/RESERVE_MSISDN_SUCCESS'
export const RESERVE_MSISDN_ERROR = 'broadband/RESERVE_MSISDN_ERROR'
export const RESERVE_MSISDN_FAILURE = 'broadband/RESERVE_MSISDN_FAILURE'

export const CHECK_MSISDN = 'broadband/CHECK_MSISDN'
export const CHECK_MSISDN_SUCCESS = 'broadband/CHECK_MSISDN_SUCCESS'
export const CHECK_MSISDN_ERROR = 'broadband/CHECK_MSISDN_ERROR'
export const CHECK_MSISDN_FAILURE = 'broadband/CHECK_MSISDN_FAILURE'

export const SAVE_INVOICE_EQUIPMENT = 'broadband/SAVE_INVOICE_EQUIPMENT'
export const SAVE_INVOICE_EQUIPMENT_SUCCESS = 'broadband/SAVE_INVOICE_EQUIPMENT_SUCCESS'
export const SAVE_INVOICE_EQUIPMENT_ERROR = 'broadband/SAVE_INVOICE_EQUIPMENT_ERROR'
export const SAVE_INVOICE_EQUIPMENT_FAILURE = 'broadband/SAVE_INVOICE_EQUIPMENT_FAILURE'

export const GET_INVOICE_EQUIPMENT_HISTORY = 'broadband/GET_INVOICE_EQUIPMENT_HISTORY'
export const GET_INVOICE_EQUIPMENT_HISTORY_SUCCESS = 'broadband/GET_INVOICE_EQUIPMENT_HISTORY_SUCCESS'
export const GET_INVOICE_EQUIPMENT_HISTORY_ERROR = 'broadband/GET_INVOICE_EQUIPMENT_HISTORY_ERROR'
export const GET_INVOICE_EQUIPMENT_HISTORY_FAILURE = 'broadband/GET_INVOICE_EQUIPMENT_HISTORY_FAILURE'

export const GET_SESSIONS_INFO = 'broadband/GET_SESSIONS_INFO'
export const GET_SESSIONS_INFO_SUCCESS = 'broadband/GET_SESSIONS_INFO_SUCCESS'
export const GET_SESSIONS_INFO_ERROR = 'broadband/GET_SESSIONS_INFO_ERROR'
export const GET_SESSIONS_INFO_FAILURE = 'broadband/GET_SESSIONS_INFO_FAILURE'

export const CREATE_SESSION = 'broadband/CREATE_SESSION'
export const CREATE_SESSION_SUCCESS = 'broadband/CREATE_SESSION_SUCCESS'
export const CREATE_SESSION_ERROR = 'broadband/CREATE_SESSION_ERROR'
export const CREATE_SESSION_FAILURE = 'broadband/CREATE_SESSION_FAILURE'

export const CLOSE_SESSION = 'broadband/CLOSE_SESSION'
export const CLOSE_SESSION_SUCCESS = 'broadband/CLOSE_SESSION_SUCCESS'
export const CLOSE_SESSION_ERROR = 'broadband/CLOSE_SESSION_ERROR'
export const CLOSE_SESSION_FAILURE = 'broadband/CLOSE_SESSION_FAILURE'

export const GET_SESSION_TASK_TYPES = 'broadband/GET_SESSION_TASK_TYPES'
export const GET_SESSION_TASK_TYPES_SUCCESS = 'broadband/GET_SESSION_TASK_TYPES_SUCCESS'
export const GET_SESSION_TASK_TYPES_ERROR = 'broadband/GET_SESSION_TASK_TYPES_ERROR'
export const GET_SESSION_TASK_TYPES_FAILURE = 'broadband/GET_SESSION_TASK_TYPES_FAILURE'

export const GET_SESSION_CLOSE_REASONS = 'broadband/GET_SESSION_CLOSE_REASONS'
export const GET_SESSION_CLOSE_REASONS_SUCCESS = 'broadband/GET_SESSION_CLOSE_REASONS_SUCCESS'
export const GET_SESSION_CLOSE_REASONS_ERROR = 'broadband/GET_SESSION_CLOSE_REASONS_ERROR'
export const GET_SESSION_CLOSE_REASONS_FAILURE = 'broadband/GET_SESSION_CLOSE_REASONS_FAILURE'

export const GET_OPERATOR_SHIFTS = 'broadband/GET_OPERATOR_SHIFTS'
export const GET_OPERATOR_SHIFTS_SUCCESS = 'broadband/GET_OPERATOR_SHIFTS_SUCCESS'
export const GET_OPERATOR_SHIFTS_ERROR = 'broadband/GET_OPERATOR_SHIFTS_ERROR'
export const GET_OPERATOR_SHIFTS_FAILURE = 'broadband/GET_OPERATOR_SHIFTS_FAILURE'

export const CREATE_OPERATOR_SHIFTS = 'broadband/CREATE_OPERATOR_SHIFTS'
export const CREATE_OPERATOR_SHIFTS_SUCCESS = 'broadband/CREATE_OPERATOR_SHIFTS_SUCCESS'
export const CREATE_OPERATOR_SHIFTS_ERROR = 'broadband/CREATE_OPERATOR_SHIFTS_ERROR'
export const CREATE_OPERATOR_SHIFTS_FAILURE = 'broadband/CREATE_OPERATOR_SHIFTS_FAILURE'

export const DELETE_OPERATOR_SHIFTS = 'broadband/DELETE_OPERATOR_SHIFTS'
export const DELETE_OPERATOR_SHIFTS_SUCCESS = 'broadband/DELETE_OPERATOR_SHIFTS_SUCCESS'
export const DELETE_OPERATOR_SHIFTS_ERROR = 'broadband/DELETE_OPERATOR_SHIFTS_ERROR'
export const DELETE_OPERATOR_SHIFTS_FAILURE = 'broadband/DELETE_OPERATOR_SHIFTS_FAILURE'

export const CREATE_AUTO_ORDER_SESSION = 'broadband/CREATE_AUTO_ORDER_SESSION'
export const CREATE_AUTO_ORDER_SESSION_SUCCESS = 'broadband/CREATE_AUTO_ORDER_SESSION_SUCCESS'
export const CREATE_AUTO_ORDER_SESSION_ERROR = 'broadband/CREATE_AUTO_ORDER_SESSION_ERROR'
export const CREATE_AUTO_ORDER_SESSION_FAILURE = 'broadband/CREATE_AUTO_ORDER_SESSION_FAILURE'

export const MODIFY_ORDER = 'broadband/MODIFY_ORDER'
export const MODIFY_ORDER_SUCCESS = 'broadband/MODIFY_ORDER_SUCCESS'
export const MODIFY_ORDER_ERROR = 'broadband/MODIFY_ORDER_ERROR'
export const MODIFY_ORDER_FAILURE = 'broadband/MODIFY_ORDER_FAILURE'

export const GET_ORDER_CHANGE_HISTORY = 'broadband/GET_ORDER_CHANGE_HISTORY'
export const GET_ORDER_CHANGE_HISTORY_SUCCESS = 'broadband/GET_ORDER_CHANGE_HISTORY_SUCCESS'
export const GET_ORDER_CHANGE_HISTORY_ERROR = 'broadband/GET_ORDER_CHANGE_HISTORY_ERROR'
export const GET_ORDER_CHANGE_HISTORY_FAILURE = 'broadband/GET_ORDER_CHANGE_HISTORY_FAILURE'

export const GET_ORDER_EDIT_SESSION_HISTORY = 'broadband/GET_ORDER_EDIT_SESSION_HISTORY'
export const GET_ORDER_EDIT_SESSION_HISTORY_SUCCESS = 'broadband/GET_ORDER_EDIT_SESSION_HISTORY_SUCCESS'
export const GET_ORDER_EDIT_SESSION_HISTORY_ERROR = 'broadband/GET_ORDER_EDIT_SESSION_HISTORY_ERROR'
export const GET_ORDER_EDIT_SESSION_HISTORY_FAILURE = 'broadband/GET_ORDER_EDIT_SESSION_HISTORY_FAILURE'

export const GET_ORDER_EDIT_SESSION = 'broadband/GET_ORDER_EDIT_SESSION'
export const GET_ORDER_EDIT_SESSION_SUCCESS = 'broadband/GET_ORDER_EDIT_SESSION_SUCCESS'
export const GET_ORDER_EDIT_SESSION_ERROR = 'broadband/GET_ORDER_EDIT_SESSION_ERROR'
export const GET_ORDER_EDIT_SESSION_FAILURE = 'broadband/GET_ORDER_EDIT_SESSION_FAILURE'

export const CREATE_ORDER_EDIT_SESSION = 'broadband/CREATE_ORDER_EDIT_SESSION'
export const CREATE_ORDER_EDIT_SESSION_SUCCESS = 'broadband/CREATE_ORDER_EDIT_SESSION_SUCCESS'
export const CREATE_ORDER_EDIT_SESSION_ERROR = 'broadband/CREATE_ORDER_EDIT_SESSION_ERROR'
export const CREATE_ORDER_EDIT_SESSION_FAILURE = 'broadband/CREATE_ORDER_EDIT_SESSION_FAILURE'

export const MODIFY_ORDER_EDIT_SESSION = 'broadband/MODIFY_ORDER_EDIT_SESSION'
export const MODIFY_ORDER_EDIT_SESSION_SUCCESS = 'broadband/MODIFY_ORDER_EDIT_SESSION_SUCCESS'
export const MODIFY_ORDER_EDIT_SESSION_ERROR = 'broadband/MODIFY_ORDER_EDIT_SESSION_ERROR'
export const MODIFY_ORDER_EDIT_SESSION_FAILURE = 'broadband/MODIFY_ORDER_EDIT_SESSION_FAILURE'

export const DELETE_ORDER_EDIT_SESSION = 'broadband/DELETE_ORDER_EDIT_SESSION'
export const DELETE_ORDER_EDIT_SESSION_SUCCESS = 'broadband/DELETE_ORDER_EDIT_SESSION_SUCCESS'
export const DELETE_ORDER_EDIT_SESSION_ERROR = 'broadband/DELETE_ORDER_EDIT_SESSION_ERROR'
export const DELETE_ORDER_EDIT_SESSION_FAILURE = 'broadband/DELETE_ORDER_EDIT_SESSION_FAILURE'

export const GET_CHANGE_ORDER = 'broadband/GET_CHANGE_ORDER'
export const GET_CHANGE_ORDER_SUCCESS = 'broadband/GET_CHANGE_ORDER_SUCCESS'
export const GET_CHANGE_ORDER_ERROR = 'broadband/GET_CHANGE_ORDER_ERROR'
export const GET_CHANGE_ORDER_FAILURE = 'broadband/GET_CHANGE_ORDER_FAILURE'

export const CHANGE_ORDER = 'broadband/CHANGE_ORDER'
export const CHANGE_ORDER_SUCCESS = 'broadband/CHANGE_ORDER_SUCCESS'
export const CHANGE_ORDER_ERROR = 'broadband/CHANGE_ORDER_ERROR'
export const CHANGE_ORDER_FAILURE = 'broadband/CHANGE_ORDER_FAILURE'

export const HANDLE_CHANGE_MANUAL_UPSALE = 'broadband/HANDLE_CHANGE_MANUAL_UPSALE'
export const HANDLE_CHANGE_MANUAL_UPSALE_SUCCESS = 'broadband/HANDLE_CHANGE_MANUAL_UPSALE_SUCCESS'
export const HANDLE_CHANGE_MANUAL_UPSALE_ERROR = 'broadband/HANDLE_CHANGE_MANUAL_UPSALE_ERROR'

export const HANDLE_CHANGE_AUTO_UPSALE = 'broadband/HANDLE_CHANGE_AUTO_UPSALE'
export const HANDLE_CHANGE_AUTO_UPSALE_SUCCESS = 'broadband/HANDLE_CHANGE_AUTO_UPSALE_SUCCESS'
export const HANDLE_CHANGE_AUTO_UPSALE_ERROR = 'broadband/HANDLE_CHANGE_AUTO_UPSALE_ERROR'

export const GET_RELOCATION_INFO = 'broadband/GET_RELOCATION_INFO'
export const GET_RELOCATION_INFO_SUCCESS = 'broadband/GET_RELOCATION_INFO_SUCCESS'
export const GET_RELOCATION_INFO_ERROR = 'broadband/GET_RELOCATION_INFO_ERROR'
export const GET_RELOCATION_INFO_FAILURE = 'broadband/GET_RELOCATION_INFO_FAILURE'
