import { all, takeEvery } from 'redux-saga/effects'
import {
  GET_SALES_REPORT_FULL,
  GET_SALES_REPORT_SHORT,
  GET_SELL_AVAILABILITY,
  GET_SHOP_TARIFFS,
  GET_SHOP_NUMBERS,
  SEARCH_SHOP_NUMBERS,
  ADD_SIM,
  SELL_ADDED_SIMS,
  CHECK_SIM_MNP,
  GET_TRANSFER_EARLIEST_TIME_SLOT,
  GET_TRANSFER_TIME_SLOTS,
  SEARCH_COUNTRIES,
  SEARCH_ADDRESSES,
  CHECK_SIM_SALE_AVAILABILITY,
  GET_AGREEMENT_FILES,
  DOWNLOAD_AGREEMENT_FILE,
  SEARCH_CODE_UFMS,
  GET_PEP_NUMBERS,
  GET_SMS_CODE,
  GET_DOCUMENT_CODE,
  CHECK_PEP_CODE,
  GET_PAPER_DOCUMENTS,
  REGISTER_SIMS,
  DOWNLOAD_REGISTER_SIM_INSTRUCTION,
  ADD_SIM_IN_ORDER,
  SALE_SIMS,
  getExistingPersonalData,
  ADD_PERSONAL_ACCOUNT_NUMBER,
  createMnpOrderSaleSim,
  CHECK_ADDRESS,
  connectBroadbandSaleSim
} from 'reducers/saleSim/saleSimReducer'
import { GET_SMEV_DATA, UPLOAD_DOCUMENT, sendDocumentSmev } from 'reducers/checkSmev/checkSmevReducer'
import {
  getSalesReportFullSaga,
  getSalesReportShortSaga,
  getSellAvailabilitySaga,
  getShopTariffsSaga,
  getShopNumbersSaga,
  searchShopNumberSaga,
  addSimSaga,
  sellAddedSimsSaga,
  checkSimMnpSaga,
  getTransferEarliestTimeSlotSaga,
  getTransferTimeSlotsSaga,
  searchCountriesSaga,
  searchAddressesSaga,
  checkSimSaleAvailabilitySaga,
  getAgreementFilesSaga,
  downloadAgreementFileSaga,
  searchCodeUFMSSaga,
  getPepNumbersSaga,
  getSmsCodeSaga,
  getDocumentCodeSaga,
  checkPepCodeSaga,
  getPaperDocumentsSaga,
  registerSimsSaga,
  downloadRegisterSimInstructionSaga,
  addSimInOrderSaga,
  saleSimSaga,
  createMnpOrderSaleSimSaga,
  getExistingPersonalDataSaga,
  addPersonalAccountNumberSaga,
  checkAddressSaga,
  connectBroadbandSaleSimSaga
} from './saleSimSaga'

import { getSmevDataWrapperSaga, sendDocumentSmevSaga, uploadDocumentSaga } from './checkSmevSaga'

export default function * () {
  yield all([
    takeEvery(GET_SELL_AVAILABILITY, getSellAvailabilitySaga),
    takeEvery(GET_SALES_REPORT_FULL, getSalesReportFullSaga),
    takeEvery(GET_SALES_REPORT_SHORT, getSalesReportShortSaga),
    takeEvery(GET_SHOP_TARIFFS, getShopTariffsSaga),
    takeEvery(GET_SHOP_NUMBERS, getShopNumbersSaga),
    takeEvery(SEARCH_SHOP_NUMBERS, searchShopNumberSaga),
    takeEvery(ADD_SIM, addSimSaga),
    takeEvery(SEARCH_COUNTRIES, searchCountriesSaga),
    takeEvery(SEARCH_CODE_UFMS, searchCodeUFMSSaga),
    takeEvery(SEARCH_ADDRESSES, searchAddressesSaga),
    takeEvery(getExistingPersonalData().type, getExistingPersonalDataSaga),
    takeEvery(SELL_ADDED_SIMS, sellAddedSimsSaga),
    takeEvery(CHECK_SIM_MNP, checkSimMnpSaga),
    takeEvery(GET_TRANSFER_EARLIEST_TIME_SLOT, getTransferEarliestTimeSlotSaga),
    takeEvery(GET_TRANSFER_TIME_SLOTS, getTransferTimeSlotsSaga),
    takeEvery(CHECK_SIM_SALE_AVAILABILITY, checkSimSaleAvailabilitySaga),
    takeEvery(GET_AGREEMENT_FILES, getAgreementFilesSaga),
    takeEvery(DOWNLOAD_AGREEMENT_FILE, downloadAgreementFileSaga),
    takeEvery(GET_PEP_NUMBERS, getPepNumbersSaga),
    takeEvery(GET_SMS_CODE, getSmsCodeSaga),
    takeEvery(GET_DOCUMENT_CODE, getDocumentCodeSaga),
    takeEvery(CHECK_PEP_CODE, checkPepCodeSaga),
    takeEvery(GET_PAPER_DOCUMENTS, getPaperDocumentsSaga),
    takeEvery(REGISTER_SIMS, registerSimsSaga),

    takeEvery(DOWNLOAD_REGISTER_SIM_INSTRUCTION, downloadRegisterSimInstructionSaga),
    takeEvery(ADD_SIM_IN_ORDER, addSimInOrderSaga),
    takeEvery(SALE_SIMS, saleSimSaga),

    takeEvery(ADD_PERSONAL_ACCOUNT_NUMBER, addPersonalAccountNumberSaga),

    takeEvery(GET_SMEV_DATA, getSmevDataWrapperSaga),

    takeEvery(createMnpOrderSaleSim().type, createMnpOrderSaleSimSaga),

    takeEvery(CHECK_ADDRESS, checkAddressSaga),
    takeEvery(UPLOAD_DOCUMENT, uploadDocumentSaga),
    takeEvery(sendDocumentSmev().type, sendDocumentSmevSaga),
    takeEvery(connectBroadbandSaleSim().type, connectBroadbandSaleSimSaga)
  ])
}
