pipeline {
    agent {
        label 'master'
    }

    environment {
        IMAGE_NAME = 'liberty-front-react'
        IMAGE_TAG = 'develop'
        DOCKERFILE_PATH = 'Dockerfile'
        json_key = credentials('yandex_pass')
        registryName = "cr.yandex/crpqhm9qhte79o09rkl7"
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {
        stage('Unit & Integration Tests, SonarQube analysis') {
            agent {
                docker { image "node:20-alpine"
                args '-u root --privileged'
                }
            }
            steps {
                script {
                        sh 'yarn install'
                        sh 'yarn test'
                        sh 'yarn add sonar-scanner'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -f ${DOCKERFILE_PATH} -t ${registryName}/${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Push Docker image to the Container Registry') {
            steps {
                sh """
                    cat ${json_key} | docker login --username json_key --password-stdin cr.yandex
                    docker push ${registryName}/${IMAGE_NAME}:${IMAGE_TAG}
                    docker logout
                """
            }
        }

        stage('Remove unused Docker image from Jenkins Node') {
            steps {
                sh 'docker images'
                sh 'docker rmi -f ${registryName}/${IMAGE_NAME}:${IMAGE_TAG}'
                sh 'docker images'
            }
        }

        stage('Deploy to Kubernetes') {
            agent {
                docker { image 'dtzar/helm-kubectl'
                args '-u root --privileged'
                }
            }
            steps {
                withCredentials([file(credentialsId: 'k8s-config-liberty', variable: 'config')]) {
                    sh 'mkdir ~/.kube'
                    sh "cp \$config ~/.kube/config && chmod 600 ~/.kube/config"
                    sh 'kubectl config get-contexts'
                    sh 'kubectl config use-context jenkins@liberty-bank'
                    sh 'kubectl get nodes'
                    sh 'kubectl patch deployment/front-react -p "{\\"spec\\":{\\"template\\":{\\"metadata\\":{\\"annotations\\":{\\"Commit\\":\\"${GIT_COMMIT}\\"}}}}}" -n dev'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
