export const REPLACE_PROCESS_STEPS = {
  NONE: 'NONE',
  SEARCH_VERIFICATION: 'SEARCH_VERIFICATION',
  CUSTOMER_DATA: 'CUSTOMER_DATA',
  SIGNING: 'SIGNING',
  RESULT: 'RESULT'
}

export const ADMIN_CATEGORY_ID = 4
export const AUTO_NOTE_ID = 7
