import { CardProduct, AccountSelectionFormPageProductInfo } from '../../model/types';
import { groupingDebitCardProduct } from './groupingDebitCardProduct';

const cards: CardProduct[] = [
  {
    id: 'e5128bf5-347c-40ba-9c0d-1d97f2f14b19',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'MASTERCARD',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 100,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 1000000,
      amountPerDayMax: 100000000,
      amountPerMonthMax: 100000000,
      withdrawalCashPerDay: 100000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'RUB',
    validityTerm: 36,
    oneUse: false,
  },
  {
    id: '8632c00f-17ee-4afe-8085-df3177c49561',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'VISA',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 100,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 1000000,
      amountPerDayMax: 100000000,
      amountPerMonthMax: 100000000,
      withdrawalCashPerDay: 100000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'RUB',
    validityTerm: 36,
    oneUse: false,
  },
  {
    id: '13e8d83f-486a-4914-8f21-359214ca0248',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'MASTERCARD',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 1,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 100000,
      amountPerDayMax: 1000000,
      amountPerMonthMax: 1000000,
      withdrawalCashPerDay: 1000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'USD',
    validityTerm: 36,
    oneUse: false,
  },
  {
    id: 'c858caad-5521-4c0d-9dda-5904cf3f45dc',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'VISA',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 1,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 100000,
      amountPerDayMax: 1000000,
      amountPerMonthMax: 1000000,
      withdrawalCashPerDay: 1000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'USD',
    validityTerm: 36,
    oneUse: false,
  },
  {
    id: 'caa0be40-05da-4d3f-80d8-42932733f2e9',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'MASTERCARD',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 1,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 100000,
      amountPerDayMax: 1000000,
      amountPerMonthMax: 1000000,
      withdrawalCashPerDay: 1000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'EUR',
    validityTerm: 36,
    oneUse: false,
  },
  {
    id: 'c7374dbd-413f-4cad-bee8-b683a647fd27',
    typeName: 'Liberty Card Virtual',
    paymentSystem: 'VISA',
    credit: false,
    active: true,
    transferFee: {
      ourClient: 0,
      partnerClient: 0.001,
      anotherClientRu: 0.3,
      anotherClientWorld: 2,
      onBankAccount: 0.5,
      byPhoneNumber: 0.5,
      minFeeWorld: 1,
    },
    withdrawalCashFee: {
      ourBank: 0,
      partnersBank: 0,
      anotherBankRu: 0,
      anotherBankWorld: 0,
      minCashFeeWorld: 0,
    },
    costPerMonth: 0,
    freeCostFrom: 0,
    servicePrice: 0,
    cardReissue: 0,
    addCardCost: 0,
    virtual: true,
    productLimit: {
      operationPerDayMax: 1000,
      operationPerMonthMax: 10000,
      amountPerOperationMax: 100000,
      amountPerDayMax: 1000000,
      amountPerMonthMax: 1000000,
      withdrawalCashPerDay: 1000000,
    },
    cashback: {
      interestPerMonth: 0,
      interestForAll: 0,
      interestForPartners: 0,
      cashbackLimit: 0,
    },
    bonusProgram: {
      partnersBonus: false,
      bestExchangeRate: false,
    },
    level: 'Classic',
    currency: 'EUR',
    validityTerm: 36,
    oneUse: false,
  },
];

describe('groupingDebitCardProduct', () => {
  test('should group cards by typeName, paymentSystem, and currency', () => {
    const expectedResult: AccountSelectionFormPageProductInfo = {
      typeName: 'Liberty Card Virtual',
      paymentSystems: ['MASTERCARD', 'VISA'],
      currencies: ['RUB', 'USD', 'EUR'],
    };

    expect(groupingDebitCardProduct(cards)).toEqual(expectedResult);
  });
});
