export const MNP_ORDER_PROCESS_STEPS = {
  NONE: 'NONE',
  TRANSFER_NUMBER: 'TRANSFER_NUMBER',
  TRANSFER_TIME: 'TRANSFER_TIME',
  DOCUMENT_DATA: 'DOCUMENT_DATA',
  SIGNING: 'SIGNING',
  RESULT: 'RESULT'
}
