export const TEXT_REPORT = {
  title: 'Отчет о заявке',
  nameCreditProduct: 'Название кредитного продукта:',
  creationDateRequest: 'Дата создания заявки:',
  statusRequest: 'Статус заявки:',
  interestRate: 'Процентная ставка:',
  currencyCredit: 'Валюта кредита:',
  requestCreditAmount: 'Запрашиваемая сумма кредита:',
  requestCreditPeriod: 'Запрашиваемый период кредита:',
  methodObtaining: 'Способ получения:',
  typeCredit: 'Тип кредита:',
  paymentCalculationScheme: 'Схема расчета платежей:',
  typeRate: 'Тип ставки:',
  getReport: 'Отправить PDF',
  requestStatus: 'Узнать статус заявки',
  cash: 'Наличные',
  card: 'Карта',
  consumer: 'Потребительский',
  target: 'Целевой',
  differentiated: 'Дифференцированная',
  annuity: 'Аннуитетная',
  linkedToCP: 'Привязанная к СР',
  fixed: 'Фиксированная',
} as const;
